go_import_path: github.com/pubnub/go/v5  
dist: xenial
language: go
os: linux

install:
  - mkdir -p $GOPATH/src/github.com/pubnub
  - go get -u github.com/wadey/gocovmerge


stages:
  - name: "test"
    if: |
      type != pull_request \
      AND tag IS blank
  - name: "code coverage"
    if: |
      type == pull_request

jobs:
  include:
    - stage: "test"
      name: 'Go 1.14.6'
      go: 1.14.6
      script: 
        - bash ./scripts/run-tests.sh -mod=mod
    - name: 'Go 1.15.12'
      go: 1.15.12
      script: 
        - bash ./scripts/run-tests.sh -mod=mod
    - name: 'Go 1.16.4'
      go: 1.16.4
      script: 
        - bash ./scripts/run-tests.sh -mod=mod
    - name: 'Go "master"'
      go: master
      script: 
        - bash ./scripts/run-tests.sh -mod=mod
    - name: 'Go "tip"'
      go: tip
      script: bash ./scripts/run-tests.sh -mod=mod
    - stage: "code coverage"
      name: 'Test & Code coverage'
      go: 1.16.4
      script: bash ./scripts/run-tests.sh -mod=mod
      after_success:
        - bash <(curl -s https://codecov.io/bash)
  allow_failures:
    - go: tip
    - go: master
  fast_finish: true
