language: go

go:
  - 1.9.7
  - 1.10.3
  - 1.11.4  
  - 1.12.1
  - master
  - tip

env:
  - DEP_VERSION=0.5.0  
  
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
go_import_path: github.com/pubnub/go  

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - mkdir -p $GOPATH/src/github.com/pubnub
  - dep ensure
  - dep status
  - go get -u github.com/wadey/gocovmerge

script:
  - bash ./scripts/run-tests.sh

after_success:
    - bash <(curl -s https://codecov.io/bash)
