language: go

go:
  - 1.6.4
  - 1.7.6
  - 1.8.5
  - 1.9.2

go_import_path: github.com/pubnub/go

install:
  - mkdir -p $GOPATH/src/github.com/pubnub
  - ls -all
  - pwd
  - echo $GOPATH
  - echo $PATH
  - go get -u github.com/golang/dep/cmd/dep
  - deps ensure
  - go get github.com/wadey/gocovmerge

script:
  - bash ./scripts/run-tests.sh

after_success:
    - bash <(curl -s https://codecov.io/bash)
