language: go

go:
  - 1.4.3
  - 1.5.3


install:
  - go get -t -v ./messaging/
  - mkdir -p $GOPATH/src/github.com/pubnub
  - ln -s $GOPATH/src/github.com/anovikov1984/go $GOPATH/src/github.com/pubnub/go
script:
  - cd messaging && go test -v -race
  - cd tests && go test -v -race
